In [1]:
X = [3 0 0; 1 1 1; 2 2 2;]

3×3 Array{Int64,2}:
 3  0  0
 1  1  1
 2  2  2

In [2]:
X[1,:]

3-element Array{Int64,1}:
 3
 0
 0

In [3]:
size(X)

(3,3)

In [4]:
size(X[1,:])

(3,)

In [5]:
v = X[1,:]

3-element Array{Int64,1}:
 3
 0
 0

In [6]:
X*v

3-element Array{Int64,1}:
 9
 3
 6

In [7]:
X[:,1]

3-element Array{Int64,1}:
 3
 1
 2

In [8]:
for i =1:3
end

In [9]:
T = [1/sqrt(2) 1/sqrt(3) 1/sqrt(6); 0 1/sqrt(3) -2/sqrt(6); 1/sqrt(2) 1/sqrt(3) 1/sqrt(6)]
for i=1:3
    X[:,i] = T*X[:,i]
end

LoadError: InexactError()

In [10]:
T = [1/sqrt(2) 1/sqrt(3) 1/sqrt(6); 0 1/sqrt(3) -2/sqrt(6); 1/sqrt(2) 1/sqrt(3) 1/sqrt(6)]
T*X[:,1]

3-element Array{Float64,1}:
  3.51517
 -1.05564
  3.51517

In [11]:
X

3×3 Array{Int64,2}:
 3  0  0
 1  1  1
 2  2  2

In [13]:
T = [1/sqrt(2) 1/sqrt(3) 1/sqrt(6); 0 1/sqrt(3) -2/sqrt(6); 1/sqrt(2) 1/sqrt(3) 1/sqrt(6)]
Y[:,1] = T*X[:,1]

LoadError: UndefVarError: Y not defined

In [14]:
index = length(X[1,:])
T = [1/sqrt(2) 1/sqrt(3) 1/sqrt(6); 0 1/sqrt(3) -2/sqrt(6); 1/sqrt(2) 1/sqrt(3) 1/sqrt(6)]
Y = zeros(3, index)
for i=1:index
    Y[:,i]= T*X[:,i]
end
Y

3×3 Array{Float64,2}:
  3.51517   1.39385   1.39385
 -1.05564  -1.05564  -1.05564
  3.51517   1.39385   1.39385